name: Keepalive

on:
  schedule:
    - cron: '0 0 1,15 * *' # 1st and 15th of each month
  workflow_dispatch: {}

jobs:
  keepalive:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2
